name: Sync with upstream and deploy to Coolify
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/iptv-org/iptv.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories -m "Auto-sync with upstream"
          git push https://${{ secrets.GITHUB_TOKEN }} HEAD:master

      - name: Trigger Coolify deploy
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://medie.dev/api/v1/deploy?uuid=cocgk0c4oc0w444g8swocs4k&force=false"
